7 @DISTANCE (MILES) BETWEEN SATELLITES (F) : 2000.
&t?_'eHv>Q(g=ZvB)d<Jr;R:Y*j@u9F8L+h7Rq6Xx5]~B,c4Gh3Lk2Qn1Vo0Zo/_Dn.Hk-Mh,Rc+W+~*\xAq)Fh(L*'Ru&Xj%^)Er$Ld#T(v"\gD'v!Me V&t@$z?_%lJ}>U&m=_}I'k<Ry;\(fDs:M~9U)h8\rD{7K*c6Rj5Yp4_uEz3L}2R1X+a0^bDa/J`.O*~-U{,\wBr+Hl*Ne)U)~(\uCl'Jb&R(w%ZkB'~$Kp#Tb"]&sGc!Q%r \`G$z@)d<QiOkJiFdD(F}JO)dQd#ZiXkTiOdM(O}TX)dZ7l @Elevation deg.20.
6y @Velocity m/ph.-100.
)d#TScRdPePhOkPnQsTwW|\*a$AeHjOmVp]s%EtKuRtW[r_q&AoBnClBAk@l%_m^o^q^t_x&B|E+aJeOiUm\p'DrKtSuZu(AGtKrOqRoSmTlTkSjRQkPmOoOrPuSyV}Z,`)@dFgMjTl\m*DKRlXk^i+BgEeGcHbHaG`FEaDbCdCfDiFlIpMsRvXx_{,G|O}W^|-E{LyQwVuYs\p]o]m]\lZmYnXpXrYt[w]z.A}FL-aScZc/BdJcRbY`0@,~F|KyNvQtRrSpSoRQPpOrNtOvPxR{V}[1@-aGbNV^`2F,M|TzZw_t3CqFnHlIjIiHhGiFEjDlDnEpGrKtOvTw[w4BIvQuYr5@pGmNiSfWbZ+\}]z^y]x\[yZzY{Y}Z[,a^c6BdGMT[b7C`K+}RzYv8@rEnIjMgOdPbQ`P*ONM+`LaLcLeNfPhTiX^i9DgKfScZ*:B|IwOsTnYj]f_b;@`A)~A|@|:_]}\~\*`\a]c_d;BeGLdRcX`<@)}GyNuUp[k=AfEaI(|KyMuNsMqMLJIrItIuIwKxNRVw\u>BsIoPkWf]a?D'{IuNpQkTfVcV`V&~V}TSR~Q'`QaRcSdUY]c_6f @Elevation deg.20.
5s @Velocity m/ph.-120.
)d<JcKaK(J~G|D|;_Y}R~J)aBe:YiPnHsAx9Z}T*bPgMkKnKpKrLMOqPpPnPlOjLhHgCg8]UhMjDl7[pRtJxB|6[+aVeQiNmMoLrMsNOPrQpRnQlPjMhIfCe5\ULfCh4ZjPmHp@t3YxT{PM,bKeKfKgLhNgOfPdQbP`N+}K{FxAw2ZuQIu1_vVwMyD|0\V,bPeLhJkHmHnIoJpKoMnNlNiMgKdGaC+~/]{UyMxDw.[QHx@z-X|RM,aIdFfEhEjFkGIjJiKfKdJ`H+}Dy,_vYrRoIm@k+WjNEj*\kUmOoJqGsDuCwCxDyEGxHwItIqHmEiBe)]aW*}OyGu(^sUqLoCo'[TpNrJtGvExDyD{EFHzIxJvIrHnFiBd&])WzPuHq%_mVjNhEg$^WRiMjKlInHpIqJKLpMnNkNgMbJ(}GwBq#\kUeM`E'|"\xTuLtEs!_ZtVuSwRyRzR{S|T{VzWwXtWpVjTdP&~LwFp _jXdP%Hz@@5`@Elevation deg.20.
4m @Velocity m/ph.-110.
)d#TScQdPfOhOkPoQtTyX~]*d$CiJmQqYu%BwIyQX^x&CwFuIsJrKpJoIHGpFrEuFyG}J+aNfRjYo_s'GvOyX{(@|HO{Vz[x_w)BuDsEqEpDoCpA@r@t@xA{CG,cLgRkXn*@qHsQtZt+BJsPqVo[m^k,AiBgBfAe@e+_]g]i]k^o,@rCuGyM|T~[-`-DbLU]a.E`M,}S{Xx\v^s/@q@p@o._]\p[r[t\w]z/@}DJ-bPdWe0@fHQeZc1BaI,P|UxYu\s^p_o_m^\[nZpZrZt[v^y2B{G}M~T\3D~M}V{^x4FtLqRmWjZg\d]b]`\[ZXbXcXfYh[j^l5CmHnOW_l6HjPgXd7@`G+{MwRsUoXlYjYhYgWVUiTjTlTnVpYq]r8BsIrPqXo9@lHiQeX`_*{:EvJrNmQjRgReRdQcPNdMfMgMiOkQlUmY_l;FkMhUe]`<E)|MvTqZk_f=CaE(}GyHwGuFEDvCwBxBzC|E}HMR|Xz_w>GsNnVi]c?D'}JvOpSkUfWbX&X}W|VT}S~RR'aSbTcWd[c_3z @Elevation deg.20.
3g @Velocity m/ph.-130.
