#!/bin/sh
# install_apl - install apl font and build test program

case `uname` in
  Darwin)
    FONTDIR=$HOME/Library/Fonts
    ;;
  *)
    FONTDIR=$HOME/.local/share/fonts
    ;;
esac

mkdir -p $FONTDIR
cp Apl385.ttf $FONTDIR

mkdir -p $HOME/.tek4010conf
cp aplkeys $HOME/.tek4010conf

if [ "`uname`" != "Darwin" ]; then
  fc-cache $FONTDIR
  fc-match "APL385 Unicode"
fi

make