const char *helpStr =
"Usage: ./tek4010 [options] COMMAND [...]\n"
"\n"
"    -h, --help      Print this help and exit.\n"
"\n"
"    -noexit         do not close window after completion of \"command\"\n"
"\n"
"    -raw            do not execute an automatic CR (carriage return) after a\n"
"                    LF (line feed)\n"
"\n"
"    -tab1           execute a blank instead of a tab to the next 8-character column\n"
"\n"
"    -b100000, -b38400, -b19200, -b9600, -b4800, -b2400, -b1200, -b600, -b300\n"
"                    Emulate a baud rate. Without one of these arguments, the baud rate\n"
"                    is 19200 baud. The original Tektronix 4010 had a maximal baud rate\n"
"                    of 9600 baud. The 4014 could support up to 100000 baud with a special\n"
"                    interface. With the small baud rates you can emulate 1970s\n"
"                    style modem performance. Early modems had a baud rate of 300.\n"
"\n"
"    -full           in this mode the tek4010 emulator creates a full screen window and\n"
"                    uses the full resolution of the 4014 with the enhanced graphics\n"
"                    module installed, scaled down to the actual window size.\n"
"                    Use ctrl-q to close the tek4010 window.\n"
"\n"
"    -fullv          in this mode the tek4010 emulator creates a decorated window\n"
"                    using the maximal vertical space available. The full resolution of\n"
"                    the 4014 with the enhanced graphics module installed is used,\n"
"                    scaled down to the actual window size\n"
"\n"
"    -ARDS           display ARDS data\n"
"\n"
"    -APL            emulate Tektronix 4013/4015 with alternative APL character set.\n"
"                    Details see below.\n"
"\n"
"    -autoClear      erase screen if a line feed is executed at the bottom of the screen.\n"
"                    This makes it sometimes easier to use tek4010 as the only terminal.\n"
"                    It is not the behaviour of the original hardware.\n"
"\n"
"    -keepsize       tek4010 sets the fontsize to normal whenever the screen is erased.\n"
"                    This option keeps the currently selected font size until it is\n"
"                    changed with a new escape sequence. Some historic plot files will\n"
"                    not reset the font size back to normal if this option is set.\n"
"\n"
"    -hidecursor     hides the cursor. Do not set while using GIN mode.\n"
"\n"
"    -wait n         Close window n seconds after completion of \"command\".\n"
"                    It does not make sense to use -noexit together with -wait.\n"
"\n"
"    -fast           Use fast rendering without fading. Recommended on slower systems.\n"
"                    This mode can be used to avoid a slow and choppy display.\n"
"                    -fast is automatically used for baud rates above 19200.\n"
;
